#training parameters
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 1000
  max_lr: 0.005          # sgd learning rate max
  min_lr: 0.001          # warmup initial learning rate
  up_epochs: 1           # warmup during first XX epochs (can be float)
  down_epochs:  20       # warmdown during second XX epochs  (can be float)
  max_momentum: 0.7      # sgd momentum max when lr is mim
  min_momentum: 0.5      # sgd momentum min when lr is max
  final_decay: 0.95      # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0001        # weight decay
  batch_size:  8         # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  save_summary: False    # Summary of weight histograms for tensorboard
  save_imgs: True        # False doesn't save anything, True saves some 
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  avg_N: 3               # average the N best models
  crop_prop:
    height: 448
    width: 448

# backbone parameters
backbone:
  name: "mobilenetv2"
  dropout: 0.01
  bn_d: 0.01
  OS: 8  # output stride
  train: True # train backbone?
  extra:
    width_mult: 1.0
    shallow_feats: True # get features before the last layer (mn2)

decoder:
  name: "aspp_residual"
  dropout: 0.01
  bn_d: 0.01
  train: True # train decoder?
  extra:
    aspp_channels: 64
    skip_os: [4]
    last_channels: 32

# classification head parameters
head:
  name: "segmentation"
  dropout: 0.01

# dataset (to find parser)
dataset:
  name: "coco"
  location: "/cache/datasets/coco/"
  workers: 12  # number of threads to get data
  img_means: #rgb
    - 0.47037394
    - 0.44669544
    - 0.40731883
  img_stds: #rgb
    - 0.27876515
    - 0.27429348
    - 0.28861644
  img_prop:
    width: 512
    height: 512
    depth: 3
  labels:
    0: 'nothing'
    1: 'person'
    2: 'bicycle'
    3: 'car'
    4: 'motorcycle'
    5: 'airplane'
    6: 'bus'
    7: 'train'
    8: 'truck'
    9: 'boat'
    10: 'traffic light'
    11: 'fire hydrant'
    12: 'stop sign'
    13: 'parking meter'
    14: 'bench'
    15: 'bird'
    16: 'cat'
    17: 'dog'
    18: 'horse'
    19: 'sheep'
    20: 'cow'
    21: 'elephant'
    22: 'bear'
    23: 'zebra'
    24: 'giraffe'
    25: 'backpack'
    26: 'umbrella'
    27: 'handbag'
    28: 'tie'
    29: 'suitcase'
    30: 'frisbee'
    31: 'skis'
    32: 'snowboard'
    33: 'sports ball'
    34: 'kite'
    35: 'baseball bat'
    36: 'baseball glove'
    37: 'skateboard'
    38: 'surfboard'
    39: 'tennis racket'
    40: 'bottle'
    41: 'wine glass'
    42: 'cup'
    43: 'fork'
    44: 'knife'
    45: 'spoon'
    46: 'bowl'
    47: 'banana'
    48: 'apple'
    49: 'sandwich'
    50: 'orange'
    51: 'broccoli'
    52: 'carrot'
    53: 'hot dog'
    54: 'pizza'
    55: 'donut'
    56: 'cake'
    57: 'chair'
    58: 'couch'
    59: 'potted plant'
    60: 'bed'
    61: 'dining table'
    62: 'toilet'
    63: 'tv'
    64: 'laptop'
    65: 'mouse'
    66: 'remote'
    67: 'keyboard'
    68: 'cell phone'
    69: 'microwave'
    70: 'oven'
    71: 'toaster'
    72: 'sink'
    73: 'refrigerator'
    74: 'book'
    75: 'clock'
    76: 'vase'
    77: 'scissors'
    78: 'teddy bear'
    79: 'hair drier'
    80: 'toothbrush'
    81: 'banner'
    82: 'blanket'
    83: 'bridge'
    84: 'cardboard'
    85: 'counter'
    86: 'curtain'
    87: 'door-stuff'
    88: 'floor-wood'
    89: 'flower'
    90: 'fruit'
    91: 'gravel'
    92: 'house'
    93: 'light'
    94: 'mirror-stuff'
    95: 'net'
    96: 'pillow'
    97: 'platform'
    98: 'playingfield'
    99: 'railroad'
    100: 'river'
    101: 'road'
    102: 'roof'
    103: 'sand'
    104: 'sea'
    105: 'shelf'
    106: 'snow'
    107: 'stairs'
    108: 'tent'
    109: 'towel'
    110: 'wall-brick'
    111: 'wall-stone'
    112: 'wall-tile'
    113: 'wall-wood'
    114: 'water-other'
    115: 'window-blind'
    116: 'window-other'
    117: 'tree-merged'
    118: 'fence-merged'
    119: 'ceiling-merged'
    120: 'sky-other-merged'
    121: 'cabinet-merged'
    122: 'table-merged'
    123: 'floor-other-merged'
    124: 'pavement-merged'
    125: 'mountain-merged'
    126: 'grass-merged'
    127: 'dirt-merged'
    128: 'paper-merged'
    129: 'food-other-merged'
    130: 'building-other-merged'
    131: 'rock-merged'
    132: 'wall-other-merged'
    133: 'rug-merged'
  labels_w:
    0: 3.30289772
    1: 3.44347075
    2: 4.45638856
    3: 4.38993873
    4: 4.40558454
    5: 4.43124634
    6: 4.3704214
    7: 4.37116607
    8: 4.39089505
    9: 4.43982977
    10: 4.47110532
    11: 4.46438403
    12: 4.4641625
    13: 4.47022578
    14: 4.42895632
    15: 4.45500307
    16: 4.38707112
    17: 4.4106653
    18: 4.42796692
    19: 4.45204959
    20: 4.4401263
    21: 4.40878283
    22: 4.45387203
    23: 4.42985916
    24: 4.43098019
    25: 4.46656527
    26: 4.43376055
    27: 4.46507904
    28: 4.46901983
    29: 4.43360579
    30: 4.47575828
    31: 4.47660484
    32: 4.47609518
    33: 4.47902746
    34: 4.47053574
    35: 4.47920049
    36: 4.47851516
    37: 4.47207879
    38: 4.4627746
    39: 4.47251257
    40: 4.45219224
    41: 4.46598228
    42: 4.43872198
    43: 4.47574847
    44: 4.47361754
    45: 4.47653982
    46: 4.3856233
    47: 4.44137513
    48: 4.46232492
    49: 4.42603155
    50: 4.45842983
    51: 4.44975287
    52: 4.46772733
    53: 4.46178419
    54: 4.35241406
    55: 4.44811407
    56: 4.41883936
    57: 4.38430288
    58: 4.39932503
    59: 4.44830829
    60: 4.34076057
    61: 4.12794364
    62: 4.43239948
    63: 4.42920318
    64: 4.42674297
    65: 4.4779212
    66: 4.47228467
    67: 4.4601095
    68: 4.464409
    69: 4.46698271
    70: 4.43035479
    71: 4.4805109
    72: 4.45518222
    73: 4.42609323
    74: 4.44834649
    75: 4.46003338
    76: 4.45381149
    77: 4.47562135
    78: 4.43113793
    79: 4.48089522
    80: 4.47869317
    81: 4.44563805
    82: 4.46413676
    83: 4.46293932
    84: 4.44642236
    85: 4.43632268
    86: 4.40910322
    87: 4.38526776
    88: 4.3944411
    89: 4.45029668
    90: 4.46144729
    91: 4.44159602
    92: 4.41370389
    93: 4.45954104
    94: 4.42862471
    95: 4.45304841
    96: 4.47323538
    97: 4.4488511
    98: 4.21416693
    99: 4.43753689
    100: 4.40023077
    101: 4.14827356
    102: 4.45886822
    103: 4.33387961
    104: 4.15029549
    105: 4.4377465
    106: 4.19835921
    107: 4.46436897
    108: 4.46873253
    109: 4.46950434
    110: 4.39793066
    111: 4.44590653
    112: 4.35002018
    113: 4.38429034
    114: 4.41615226
    115: 4.45421316
    116: 4.33110842
    117: 3.65425719
    118: 4.26863963
    119: 4.34291598
    120: 3.44555095
    121: 4.3511337
    122: 4.26604345
    123: 4.27425755
    124: 4.13640191
    125: 4.37059881
    126: 3.90903173
    127: 4.27844617
    128: 4.40569505
    129: 4.37009275
    130: 4.04897801
    131: 4.41257335
    132: 3.66257514
    133: 4.38268395
  color_map: # bgr
    0: [0, 0, 0]
    1: [220, 20, 60]
    2: [119, 11, 32]
    3: [0, 0, 142]
    4: [0, 0, 230]
    5: [106, 0, 228]
    6: [0, 60, 100]
    7: [0, 80, 100]
    8: [0, 0, 70]
    9: [0, 0, 192]
    10: [250, 170, 30]
    11: [100, 170, 30]
    12: [220, 220, 0]
    13: [175, 116, 175]
    14: [250, 0, 30]
    15: [165, 42, 42]
    16: [255, 77, 255]
    17: [0, 226, 252]
    18: [182, 182, 255]
    19: [0, 82, 0]
    20: [120, 166, 157]
    21: [110, 76, 0]
    22: [174, 57, 255]
    23: [199, 100, 0]
    24: [72, 0, 118]
    25: [255, 179, 240]
    26: [0, 125, 92]
    27: [209, 0, 151]
    28: [188, 208, 182]
    29: [0, 220, 176]
    30: [255, 99, 164]
    31: [92, 0, 73]
    32: [133, 129, 255]
    33: [78, 180, 255]
    34: [0, 228, 0]
    35: [174, 255, 243]
    36: [45, 89, 255]
    37: [134, 134, 103]
    38: [145, 148, 174]
    39: [255, 208, 186]
    40: [197, 226, 255]
    41: [171, 134, 1]
    42: [109, 63, 54]
    43: [207, 138, 255]
    44: [151, 0, 95]
    45: [9, 80, 61]
    46: [84, 105, 51]
    47: [74, 65, 105]
    48: [166, 196, 102]
    49: [208, 195, 210]
    50: [255, 109, 65]
    51: [0, 143, 149]
    52: [179, 0, 194]
    53: [209, 99, 106]
    54: [5, 121, 0]
    55: [227, 255, 205]
    56: [147, 186, 208]
    57: [153, 69, 1]
    58: [3, 95, 161]
    59: [163, 255, 0]
    60: [119, 0, 170]
    61: [0, 182, 199]
    62: [0, 165, 120]
    63: [183, 130, 88]
    64: [95, 32, 0]
    65: [130, 114, 135]
    66: [110, 129, 133]
    67: [166, 74, 118]
    68: [219, 142, 185]
    69: [79, 210, 114]
    70: [178, 90, 62]
    71: [65, 70, 15]
    72: [127, 167, 115]
    73: [59, 105, 106]
    74: [142, 108, 45]
    75: [196, 172, 0]
    76: [95, 54, 80]
    77: [128, 76, 255]
    78: [201, 57, 1]
    79: [246, 0, 122]
    80: [191, 162, 208]
    81: [255, 255, 128]
    82: [147, 211, 203]
    83: [150, 100, 100]
    84: [168, 171, 172]
    85: [146, 112, 198]
    86: [210, 170, 100]
    87: [92, 136, 89]
    88: [218, 88, 184]
    89: [241, 129, 0]
    90: [217, 17, 255]
    91: [124, 74, 181]
    92: [70, 70, 70]
    93: [255, 228, 255]
    94: [154, 208, 0]
    95: [193, 0, 92]
    96: [76, 91, 113]
    97: [255, 180, 195]
    98: [106, 154, 176]
    99: [230, 150, 140]
    100: [60, 143, 255]
    101: [128, 64, 128]
    102: [92, 82, 55]
    103: [254, 212, 124]
    104: [73, 77, 174]
    105: [255, 160, 98]
    106: [255, 255, 255]
    107: [104, 84, 109]
    108: [169, 164, 131]
    109: [225, 199, 255]
    110: [137, 54, 74]
    111: [135, 158, 223]
    112: [7, 246, 231]
    113: [107, 255, 200]
    114: [58, 41, 149]
    115: [183, 121, 142]
    116: [255, 73, 97]
    117: [107, 142, 35]
    118: [190, 153, 153]
    119: [146, 139, 141]
    120: [70, 130, 180]
    121: [134, 199, 156]
    122: [209, 226, 140]
    123: [96, 36, 108]
    124: [96, 96, 96]
    125: [64, 170, 64]
    126: [152, 251, 152]
    127: [208, 229, 228]
    128: [206, 186, 171]
    129: [152, 161, 64]
    130: [116, 112, 0]
    131: [0, 114, 143]
    132: [102, 102, 156]
    133: [250, 141, 255]
